name: Create PR from Dev to Main

on:
  push:
    branches:
      - dev

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Automatically created PR from Dev to Main
          branch: dev
          base: main
          body: |
            This PR was automatically created by a GitHub Actions workflow.
          token: ${{ secrets.GITHUB_TOKEN }}
